export const VEHICULES = {
    "car": {
        BASE_PRICE: 45,
        KM_THRESHOLD: 200,
        KM_PRICE: 0.25,
        INSURANCE_PRICE: 12,
        INSURANCE_PRICE_UNDER_25: 8,
        DEPOSIT: 800,
        LABEL: "Car rental",
        TAIL_LIFT_PRICE: 0,
        GEAR_PRICE: 0,
        SP_BATTERY_PRICE: 0 ,
    },
    "van": {
        BASE_PRICE: 70,
        KM_THRESHOLD: 150,
        KM_PRICE: 0.35,
        INSURANCE_PRICE: 18,
        INSURANCE_PRICE_UNDER_25: 8,
        DEPOSIT: 1500,
        LABEL: "Van rental",
        TAIL_LIFT_PRICE: 15,
        GEAR_PRICE: 0,
        SP_BATTERY_PRICE: 0,
    },
    "motorbike": {
        BASE_PRICE: 38,
        KM_THRESHOLD: 300,
        KM_PRICE: 0.18,
        INSURANCE_PRICE: 15,
        INSURANCE_PRICE_UNDER_25: 8,
        DEPOSIT: 600,
        LABEL: "Motorbike rental",
        GEAR_PRICE: 9,
        TAIL_LIFT_PRICE: 0,
        SP_BATTERY_PRICE: 0,
    },
    "bike": {
        BASE_PRICE: 12,
        KM_THRESHOLD: 0,
        KM_PRICE: 0,
        INSURANCE_PRICE: 2,
        INSURANCE_PRICE_UNDER_25: 0,
        DEPOSIT: 150,
        LABEL: "Electric bike rental",
        TAIL_LIFT_PRICE: 0,
        GEAR_PRICE: 0,
        SP_BATTERY_PRICE: 4,
    },
}